# Generated by Django 5.2.17 on 2026-10-04 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homework',
            options={'ordering': ['-date', 'subject'], 'verbose_name': 'Домашнее задание', 'verbose_name_plural': 'Домашние задания'},
        ),
        migrations.AlterModelOptions(
            name='homeworkfile',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Прикрепленный файл', 'verbose_name_plural': 'Прикрепленные файлы'},
        ),
        migrations.AlterModelOptions(
            name='homeworktask',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Пункт задания', 'verbose_name_plural': 'Пункты заданий'},
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['weekday', 'lesson_number'], 'verbose_name': 'Занятие в расписании', 'verbose_name_plural': 'Расписание'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['name'], 'verbose_name': 'Предмет', 'verbose_name_plural': 'Предметы'},
        ),
        migrations.AlterField(
            model_name='homework',
            name='date',
            field=models.DateField(verbose_name='Дата выполнения'),
        ),
        migrations.AlterField(
            model_name='homeworkfile',
            name='file_type',
            field=models.CharField(choices=[('photo', 'Фотография'), ('solution', 'Решение'), ('other', 'Другое')], default='photo', max_length=20, verbose_name='Тип файла'),
        ),
        migrations.AlterField(
            model_name='homeworktask',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Порядок сортировки'),
        ),
        migrations.AlterField(
            model_name='homeworktask',
            name='text',
            field=models.TextField(verbose_name='Текст задания'),
        ),
    ]
