# Generated by Django 5.2.17 on 2026-10-04 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0002_alter_homework_options_alter_homeworkfile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='is_online',
            field=models.BooleanField(default=False, verbose_name='Онлайн занятие'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='room',
            field=models.CharField(blank=True, max_length=50, verbose_name='Кабинет / Аудитория'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='lesson_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Номер пары'),
        ),
    ]
