# Generated by Django 5.2.17 on 2026-10-04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homework', '0003_schedule_is_online_schedule_room_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationInvite',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'code_digest',
                    models.CharField(editable=False, max_length=64, unique=True),
                ),
                (
                    'label',
                    models.CharField(blank=True, max_length=100, verbose_name='Для кого'),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('expires_at', models.DateTimeField(verbose_name='Истекает')),
                (
                    'used_at',
                    models.DateTimeField(blank=True, null=True, verbose_name='Использовано'),
                ),
                (
                    'created_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='issued_registration_invites',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Создал',
                    ),
                ),
                (
                    'used_by',
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='registration_invite',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Зарегистрировался',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Приглашение на регистрацию',
                'verbose_name_plural': 'Приглашения на регистрацию',
                'ordering': ['-created_at'],
            },
        ),
    ]
